apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- default.yaml

configurations:
- configuration.yaml

images:
- name: default-storage-initilizer
  newName: kserve/storage-initializer
  newTag: latest
- name: default-hf-storage-initilizer
  newName: kserve/hf-storage-initializer
  newTag: latest